version: '3.7'

services:
  # MongoDB
  cadmus-ingra-mongo:
    image: mongo
    container_name: cadmus-ingra-mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    command: mongod --logpath=/dev/null
    ports:
      - 27017:27017
    networks:
      - cadmus-ingra-network

  # PostgreSQL
  cadmus-ingra-pgsql:
    image: postgres
    container_name: cadmus-ingra-pgsql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    networks:
      - cadmus-ingra-network

  # Biblio API
  cadmus-biblio-api:
    image: vedph2020/cadmus-biblio-api:5.0.0
    container_name: cadmus-biblio-api
    ports:
      - 61691:80
    depends_on:
      - cadmus-ingra-mongo
      - cadmus-ingra-pgsql
    environment:
      - CONNECTIONSTRINGS__DEFAULT=mongodb://cadmus-ingra-mongo:27017/{0}
      - CONNECTIONSTRINGS__BIBLIO=Server=cadmus-ingra-pgsql;port=5432;Database={0};User Id=postgres;Password=postgres;Include Error Detail=True
      - SEED__BIBLIODELAY=50
      - SERILOG__CONNECTIONSTRING=mongodb://cadmus-ingra-mongo:27017/{0}-log
      - STOCKUSERS__0__PASSWORD=P4ss-W0rd!
    networks:
      - cadmus-ingra-network

  # Cadmus API
  cadmus-ingra-api:
    image: vedph2020/cadmus-ingra-api:4.0.0
    ports:
      - 39447:80
    depends_on:
      - cadmus-ingra-mongo
      - cadmus-ingra-pgsql
    environment:
      - CONNECTIONSTRINGS__DEFAULT=mongodb://cadmus-ingra-mongo:27017/{0}
      - CONNECTIONSTRINGS__INDEX=Server=cadmus-ingra-pgsql;port=5432;Database={0};User Id=postgres;Password=postgres;Include Error Detail=True
      - SEED__INDEXDELAY=25
      - MESSAGING__APIROOTURL=http://cadmusapi.azurewebsites.net
      - MESSAGING__APPROOTURL=http://cadmusapi.com/
      - MESSAGING__SUPPORTEMAIL=support@cadmus.com
      - SERILOG__CONNECTIONSTRING=mongodb://cadmus-ingra-mongo:27017/{0}-log
      - STOCKUSERS__0__PASSWORD=P4ss-W0rd!
    networks:
      - cadmus-ingra-network

  # Cadmus app
  cadmus-ingra-app:
    image: vedph2020/cadmus-ingra-app:2.0.0
    container_name: cadmus-ingra-app
    ports:
      - 4200:80
    depends_on:
      - cadmus-ingra-api
    networks:
      - cadmus-ingra-network

networks:
  cadmus-ingra-network:
    driver: bridge
